package Editor;

public enum CubeType {

	STONE, WALL, WOOD, GRASS, MIDHEALTH, HASTE, AMMO, MIDARMOR, REGENERATION, ULTRADAMAGE, UNTOUCHABLE, ROCKETLAUNCHER, CHAINSAW, LASER, SHOTGUN, ANVIL, BOX, BRICK, COBBLESTONE, COBBLESTONEMESSY, DIRT, DIRT2, DISPENSER, GOLD, GRAVEL, ICE, IRON, IRONPANEL, LANTERN, LAPIS, MYCELIUM, NETHERBRICK, NETHER, OBSIDIAN, PRISMARINE, QUARZ, QUARZ2, SAND, SANDSTONE, SANDSTONE2, SNOW, STONEBRICK, STONECARVED, STONEFLOOR, STONEMOSSY, WOOD2, WOOD3, WOOD4, WOOD5, BLACK, BLUE, BROWN, GRAY, GREEN, LIGHTBLUE, ORANGE, PINK, PURPLE, RED, WHITE, YELLOW, RIFLE, SNIPER, MINHEALTH, MAXHEALTH, MINARMOR, MAXARMOR;
}
